### ISSUE TITLE
lastTwoCharactersOfString assumes string length sufficient

### ISSUE THREAD

**Issue by jamorham** [hackingtype1/xDrip-Experimental#7]
The string manipulation method in Extensions.java assumes strings will be at least 2 characters long:

https://github.com/hackingtype1/xDrip-Experimental/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/G5Model/Extensions.java#L25L29

```
    public static String lastTwoCharactersOfString(String s) {
        return s.substring(s.length() - 2);
    }
```

This is called for example with a list of bonded device names. If one of those has a single character name it will cause an exception and presumably force close the app.

You could add a string length check wherever you call this method or replace it with something which can tolerate shorter names and return something indicating the error state but not risking false matches.

Perhaps like this?

```
   public static String lastTwoCharactersOfString(String s) {
        return s.length()>1 ? s.substring(s.length() - 2) : "ERR-"+s;
    }
```

**Comment by hackingtype1** [comment]
good catch, it will be in the next push to the g5-beta branch. thx
